name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - https://anaconda.org/conda-forge/mysql-connector-python/8.0.33/download/win-64/mysql-connector-python-8.0.33-py39h725d275_0.conda
  - ipywidgets
  - xeus-python
  - pandas <2




  

