name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - mysql-connector-python==8.0.28
  - ipywidgets
  - xeus-python
  - pandas <2




  

